version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "getSignalCloud"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ukqyx4kfmbnl"
s3_prefix = "getSignalCloud"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

